version: '3'
services:
  redis:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  mysql:
    image: mysql:5.7.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      - ./mysql:/var/lib/mysql